name: Terraform Workflow
# name for the workflow

on:
  pull_request:
    branches:
      - main
#runs on the pull request made 

jobs:
  terraform:
    runs-on: ubuntu-latest
# runs the job on ubuntu lates

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# first step is checkout the from github repo

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
#this step ensure the setup of the terraform with the version    

      - name: Terraform Init
        run: terraform init
# runs terraform init to initalize the terraform

      - name: Terraform Validate
        run: terraform validate
# runs terraform validate to validate the code for syntax errors

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        continue-on-error: true
#runs terraform plan to show the changes or deployemnts to be made

      - name: Comment Plan Output
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('tfplan', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Terraform plan output:\n```\n' + planOutput + '\n```'
            });
# outputs the plan details on pr for the review if accepted runs the next steps
# or else if rejected terminates the workflow here itself

      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve
